new_words = {  
     'all in': 4.0,
     '🚀': 4.0,
     'moon': 3.5,
     'highs': 2.0,
     'mooning': 3.5,
     'long': 2.0,
     'short': -2.0,
     'call': 4.0,
     'calls': 4.0,    
     'put': -4.0,
     'puts': -4.0,    
     'tendie': 2.0,
     'tendies': 3.0,     
     'overvalued': -3.0,
     'undervalued': 3.0,
     'buy': 4.0,
     'sell': -4.0,
     'gone': -1.0,
     'gtfo': -1.7,
     'paper': 1.0,
     'bullish': 3.7,
     'bearish': -3.7,
     'bagholder': -2.0,
     'stonk': 2.5,
     'green': 2.5,
     'money': 0.5,
     'print': 2.2,
     'rocket': 3.0,
     'bull': 3.0,
     'bear': -3.0,
     'pumping': -1.0,
     'sus': -3.0,
     'rip': -4.0,
     'downgrade': -3.0,
     'upgrade': 3.0,     
     'maintain': 1.0,          
     'pump': 1.9,
     'hot': 1.9,
     'drop': -2.5,
     'rebound': 1.5,
     'yolo'  :3.5,
     'gain'  :3,
     'up'  :2.0,
     'dip'  :2,
     'good'  :2.5,
     'love': 3.0,
     'red'  : -2.5,
     'bad'  :-2.5,
     'hate': -3.0,
     'hold'  : 1.0,
     'hodl'  : 0.5,
     'paper hands': 1.0,
     'diamond hands': 2.0,
     'crack': 2.5,}